### ISSUE TITLE
Got error when the target server dirctory does not exist

### ISSUE THREAD

**Issue by LinuxSuRen** [mayth/go-simple-upload-server#12]
I start this server by command `./server tmp`. Then upload a file by below command:

`curl -Ffile=@util.go 'http://localhost:25478/upload?token=b30731d81df7fc22338d'`

An error will return like this:

`{"ok":false,"error":"open tmp/util.go: no such file or directory"}`

**Comment by mayth** [comment]
In v2, if the document root directory does not exist, it is created on the first upload.
