### ISSUE TITLE
Upload to Subdirectory not possible

### ISSUE THREAD

**Issue by keefien** [mayth/go-simple-upload-server#18]
At the moment there is no upload to Subdirectories possible, uploaded files will be always stored in the root directory of /upload. If a curl with /dir/file is executed you will always get "curl: (22) The requested URL returned error: 404 "

See following examples:
curl -X PUT -k -f -Ffile=@<filename> <URL>/files/<subdir>/<filename>?token=<token>
or
curl -X POST -k -f -Ffile=@<filename> <URL>/upload/<subdir>?token=<token>

**Comment by cr1st1p** [comment]
@keefien there is PR #15 that will probably solve this (I also need it), but I see it just sits there and doesn't get merged :-(

**Comment by mayth** [comment]
v2 now supports upload to & get from sub directories. Please consider using v2.
