### ISSUE TITLE
Is any chance to modify the original filename?

### ISSUE THREAD

**Issue by YacheLee** [mayth/go-simple-upload-server#2]
I use this image for a little while.
It is great, but it seems to have nothing about modifying file name automatically.
"Automatically" means that I upload from browser, so I can't change the filename, before upload.
Could you add feature on this?

**Comment by mayth** [comment]
Thank you for your feedback.
Let me confirm if I got it. Did you mean that you want to specify the filename explicitly on uploading?

**Comment by YacheLee** [comment]
Yes.  Or use time-based random as filename.
Because I need to ensure that I don't make any duplicated files.
Thank you~ I Love this image which is useful.

**Comment by mayth** [comment]
I think you can use `PUT /files/[filename]`. This can be used to create a new file, not only to update an existing file.
Could it be that this end-point doesn't work correctly?

> Because I need to ensure that I don't make any duplicated files.

`HEAD /files/[filename]` might meet your needs if you don't care about the network cost.
(it is undocumented, sorry.)

**Comment by YacheLee** [comment]
I'm glad to see this without spending you more time to add feature~
Thank you.
