### ISSUE TITLE
CORS Policy

### ISSUE THREAD

**Issue by LucasLelaidier** [mayth/go-simple-upload-server#22]
Hi !
Im trying to use this api but the CORS Policy is disabled on the server.
Is there a way to enable it easily ?

Thanks !

**Comment by mayth** [comment]
I have merged #11. Now CORS feature is supported.
You can enable CORS support by adding `-cors` option (it is disabled by default).
This just adds `Access-Control-Allow-Origin: *` to the response header. If you need more fine-grained control, please consider using reverse proxy (e.g. nginx). Currently, I have no plan to enhance this feature.
If you have any further question, feel free to re-open this issue :-)
