### ISSUE TITLE
Undefined NewServer on launch

### ISSUE THREAD

**Issue by yuppox** [mayth/go-simple-upload-server#33]
I'm seeing `./simple_upload_server.go:66:12: undefined: NewServer` when I try to use this.

Is there some module it needs?

**Comment by mayth** [comment]
I guess that you did `go run simple_upload_server.go`.
`NewServer` is defined in `server.go`, so Go compiler can't find it if you pass only `simple_upload_server.go` to `go run`.

To run this app, I recommend that:

* `go build` then `./simple_upload_server ...`
* `go run *.go`

**Comment by mayth** [comment]
feel free to reopen this issue if you still have the problem.
