### ISSUE TITLE
integrating with n8n

### ISSUE THREAD

**Issue by stefangweichinger** [mayth/go-simple-upload-server#38]
I am currently trying to upload a html file to a container running your image, by using a "HTTP Request" node in [n8n](https://n8n.io).

The previous step in my workflow writes to "/tmp/index.html", I have no way of providing a path without a directory so far.

Can I POST to your container using something like "@/tmp/index.html" also?

![image](https://user-images.githubusercontent.com/2673904/207800610-57a4dd07-b819-48c8-bdca-9bdffe2b68f5.png)

Additional: what about cleaning up? How to remove the file after processing things?

Thanks for any help, Stefan

**Comment by mayth** [comment]
@stefangweichinger 
Sorry for late response.
This seems to be a HTTP client usage issue, not a server issue. Please find n8n's document for file uploading.

> Additional: what about cleaning up? How to remove the file after processing things?

No, there is no way to clean up the uploaded files and this server does not support deleting files.
If you are using this server in the container, consider setting the document root to the "ephemeral" directory such as a directory that is not mounted to any volumes. In such usage, recreating the container cleans all files.
