### ISSUE TITLE
Fixed tags for Docker releases

### ISSUE THREAD

**Issue by sgeffken** [mayth/go-simple-upload-server#41]
Hey there,

i just found your project last week and used it in a test environment for integration-testing.
Unfortunately, your changes last weekend broke my integration as I was using the :latest tag.

It would be awesome if you could publish your release tags also as docker image tags on dockerhub.

Would really appreciate that.
Best regards!

**Comment by mayth** [comment]
Thank you for your suggestion, and sorry for inconvenience.
I've pushed `v1` image now.
It is built with `v1` branch. However, the builder image and the runtime image are updated (see the latest commit to `v1`).

I will continue working to push images by release tags from CI.

**Comment by sgeffken** [comment]
Thank you very much, works like a charm.
