### ISSUE TITLE
Could you add a simple HTTPS support?

### ISSUE THREAD

**Issue by antmak** [mayth/go-simple-upload-server#8]
Could you add a simple HTTPS support please?

**Comment by mayth** [comment]
Sorry for late reply.
TLS support is added by commit 5b75b48 (tagged as [v1.1](https://github.com/mayth/go-simple-upload-server/tree/v1.1)).
It works (at least) on my machine, but if you find some bugs about this feature, please submit an issue 😉 
Thanks!
